import coreWebVitals from 'eslint-config-next/core-web-vitals';
import typescript from 'eslint-config-next/typescript';

/**
 * eslint-config-next 16 ships a native flat config, so the FlatCompat shim
 * that earlier versions needed is gone.
 */
const eslintConfig = [
  ...coreWebVitals,
  ...typescript,
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'out/**',
      // Generated by Next and not ours to lint.
      'next-env.d.ts',
    ],
  },
  {
    rules: {
      // Underscore-prefixed parameters mark a deliberately unused argument —
      // used in lib/checkout.ts, where the signature is the contract a real
      // payment gateway will implement against.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
];

export default eslintConfig;
