/**
 * generate-art.mjs — original generative saree artwork for Kanchi Vastra.
 *
 * WHY THIS EXISTS
 * ---------------
 * This project ships with no licensed saree photography. Rather than scrape
 * images from other businesses (never acceptable) or drop in grey boxes, we
 * compose each demo image from scratch as an SVG that follows the real
 * anatomy of a Kanchipuram saree: a woven body scattered with buttas, a
 * contrast korvai border, a dense zari pallu, and light falling across the
 * drape. Every file below is generated by this script and is therefore
 * unambiguously ours to use.
 *
 * REPLACING IT
 * ------------
 * Delete /public/images/products/* and /public/images/editorial/*, drop in
 * real photography with the same filenames, and nothing in the UI changes.
 *
 * Run:  npm run gen:art
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SPEC = JSON.parse(readFileSync(join(ROOT, 'src', 'content', 'art-specs.json'), 'utf8'));

/* -------------------------------------------------------------------------
   Deterministic PRNG — the same slug always produces the same cloth, so the
   catalogue does not reshuffle itself on every build.
   ------------------------------------------------------------------------- */
function makeRng(seedStr) {
  let h = 2166136261;
  for (let i = 0; i < seedStr.length; i++) {
    h ^= seedStr.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return function rng() {
    h += 0x6d2b79f5;
    let t = h;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/* ---- colour helpers ----------------------------------------------------- */
const hex = (c) => {
  const v = c.replace('#', '');
  return [parseInt(v.slice(0, 2), 16), parseInt(v.slice(2, 4), 16), parseInt(v.slice(4, 6), 16)];
};
/** Relative luminance, used to decide whether light cloth needs darker shading. */
const luma = (c) => {
  const [r, g, b] = hex(c);
  return (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255;
};
const mix = (a, b, t) => {
  const [r1, g1, b1] = hex(a);
  const [r2, g2, b2] = hex(b);
  const to = (x, y) =>
    Math.round(x + (y - x) * t)
      .toString(16)
      .padStart(2, '0');
  return `#${to(r1, r2)}${to(g1, g2)}${to(b1, b2)}`;
};

/* -------------------------------------------------------------------------
   MOTIF LIBRARY — buttas drawn as vector paths.
   Each returns markup positioned at (cx, cy) with radius r.
   ------------------------------------------------------------------------- */
const motifs = {
  /* Eight-petal lotus — the most common Kanchipuram butta. */
  lotus(cx, cy, r) {
    let out = '';
    for (let i = 0; i < 8; i++) {
      const deg = i * 45;
      out += `<ellipse cx="${cx}" cy="${(cy - r * 0.54).toFixed(1)}" rx="${(r * 0.19).toFixed(1)}" ry="${(r * 0.54).toFixed(1)}" transform="rotate(${deg} ${cx} ${cy})"/>`;
    }
    return `${out}<circle cx="${cx}" cy="${cy}" r="${(r * 0.17).toFixed(1)}"/>`;
  },

  /* Peacock plume — a fan of arcs, each tipped with an eye. */
  peacock(cx, cy, r) {
    let out = '';
    for (let i = -2; i <= 2; i++) {
      const a = (i * 21 - 90) * (Math.PI / 180);
      const ex = cx + Math.cos(a) * r * 0.86;
      const ey = cy + r * 0.72 + Math.sin(a) * r * 0.86;
      const mx = cx + Math.cos(a) * r * 0.42 - i * r * 0.1;
      const my = cy + r * 0.72 + Math.sin(a) * r * 0.42;
      out += `<path d="M${cx} ${(cy + r * 0.78).toFixed(1)} Q${mx.toFixed(1)} ${my.toFixed(1)} ${ex.toFixed(1)} ${ey.toFixed(1)}" fill="none" stroke="currentColor" stroke-width="${(r * 0.09).toFixed(2)}" stroke-linecap="round"/>`;
      out += `<circle cx="${ex.toFixed(1)}" cy="${ey.toFixed(1)}" r="${(r * 0.13).toFixed(1)}"/>`;
    }
    return out;
  },

  /* Mango / paisley butta with an inner echo. */
  mango(cx, cy, r) {
    const p = (k) =>
      `M${cx} ${(cy + r * 0.95 * k).toFixed(1)} ` +
      `C${(cx - r * 0.78 * k).toFixed(1)} ${(cy + r * 0.5 * k).toFixed(1)} ${(cx - r * 0.55 * k).toFixed(1)} ${(cy - r * 0.85 * k).toFixed(1)} ${(cx + r * 0.12 * k).toFixed(1)} ${(cy - r * 0.95 * k).toFixed(1)} ` +
      `C${(cx + r * 0.66 * k).toFixed(1)} ${(cy - r * 0.55 * k).toFixed(1)} ${(cx + r * 0.74 * k).toFixed(1)} ${(cy + r * 0.35 * k).toFixed(1)} ${cx} ${(cy + r * 0.95 * k).toFixed(1)} Z`;
    return `<path d="${p(1)}" fill="none" stroke="currentColor" stroke-width="${(r * 0.1).toFixed(2)}"/><path d="${p(0.52)}"/>`;
  },

  /* Rudraksha — concentric rings, a traditional border and body motif. */
  rudraksha(cx, cy, r) {
    return (
      `<circle cx="${cx}" cy="${cy}" r="${(r * 0.9).toFixed(1)}" fill="none" stroke="currentColor" stroke-width="${(r * 0.1).toFixed(2)}"/>` +
      `<circle cx="${cx}" cy="${cy}" r="${(r * 0.56).toFixed(1)}" fill="none" stroke="currentColor" stroke-width="${(r * 0.08).toFixed(2)}"/>` +
      `<circle cx="${cx}" cy="${cy}" r="${(r * 0.2).toFixed(1)}"/>`
    );
  },

  /* Faceted diamond butta. */
  diamond(cx, cy, r) {
    return (
      `<path d="M${cx} ${(cy - r).toFixed(1)} L${(cx + r * 0.66).toFixed(1)} ${cy} L${cx} ${(cy + r).toFixed(1)} L${(cx - r * 0.66).toFixed(1)} ${cy} Z" fill="none" stroke="currentColor" stroke-width="${(r * 0.11).toFixed(2)}"/>` +
      `<path d="M${cx} ${(cy - r * 0.44).toFixed(1)} L${(cx + r * 0.29).toFixed(1)} ${cy} L${cx} ${(cy + r * 0.44).toFixed(1)} L${(cx - r * 0.29).toFixed(1)} ${cy} Z"/>`
    );
  },

  /* Kolam — the looped dot-lattice drawn on South Indian thresholds. */
  kolam(cx, cy, r) {
    let out = `<circle cx="${cx}" cy="${cy}" r="${(r * 0.15).toFixed(1)}"/>`;
    for (let i = 0; i < 4; i++) {
      const deg = i * 90;
      out +=
        `<path d="M${cx} ${(cy - r * 0.22).toFixed(1)} ` +
        `C${(cx + r * 0.62).toFixed(1)} ${(cy - r * 0.86).toFixed(1)} ${(cx + r * 0.86).toFixed(1)} ${(cy + r * 0.2).toFixed(1)} ${cx} ${(cy + r * 0.22).toFixed(1)}" ` +
        `fill="none" stroke="currentColor" stroke-width="${(r * 0.1).toFixed(2)}" stroke-linecap="round" transform="rotate(${deg} ${cx} ${cy})"/>`;
    }
    return out;
  },

  /* Stepped temple spire, used as a body butta as well as in borders. */
  temple(cx, cy, r) {
    const w = r * 1.5;
    const h = r * 1.7;
    const x = cx - w / 2;
    const y = cy + h / 2;
    const s = w / 6;
    const t = h / 3;
    const pts = [
      [x, y],
      [x, y - t],
      [x + s, y - t],
      [x + s, y - 2 * t],
      [x + 2 * s, y - 2 * t],
      [x + 2 * s, y - h],
      [x + 4 * s, y - h],
      [x + 4 * s, y - 2 * t],
      [x + 5 * s, y - 2 * t],
      [x + 5 * s, y - t],
      [x + 6 * s, y - t],
      [x + 6 * s, y],
    ];
    return `<path d="M${pts.map((p) => `${p[0].toFixed(1)} ${p[1].toFixed(1)}`).join(' L')} Z"/>`;
  },
};

/* Stepped temple teeth that run the length of a korvai border. */
function templeTeeth({ x, y, width, height, count, flip = false }) {
  const w = width / count;
  let d = '';
  for (let i = 0; i < count; i++) {
    const x0 = x + i * w;
    const s = w / 3;
    const t = height / 2;
    d += flip
      ? `M${x0.toFixed(1)} ${y.toFixed(1)} L${x0.toFixed(1)} ${(y + t).toFixed(1)} L${(x0 + s).toFixed(1)} ${(y + t).toFixed(1)} L${(x0 + s).toFixed(1)} ${(y + height).toFixed(1)} L${(x0 + 2 * s).toFixed(1)} ${(y + height).toFixed(1)} L${(x0 + 2 * s).toFixed(1)} ${(y + t).toFixed(1)} L${(x0 + 3 * s).toFixed(1)} ${(y + t).toFixed(1)} L${(x0 + 3 * s).toFixed(1)} ${y.toFixed(1)} Z `
      : `M${x0.toFixed(1)} ${(y + height).toFixed(1)} L${x0.toFixed(1)} ${(y + t).toFixed(1)} L${(x0 + s).toFixed(1)} ${(y + t).toFixed(1)} L${(x0 + s).toFixed(1)} ${y.toFixed(1)} L${(x0 + 2 * s).toFixed(1)} ${y.toFixed(1)} L${(x0 + 2 * s).toFixed(1)} ${(y + t).toFixed(1)} L${(x0 + 3 * s).toFixed(1)} ${(y + t).toFixed(1)} L${(x0 + 3 * s).toFixed(1)} ${(y + height).toFixed(1)} Z `;
  }
  return d;
}

/* -------------------------------------------------------------------------
   THE CLOTH — one 1000x1400 composition per colourway. Individual images are
   just different viewBox crops of this same weave, which is why a product's
   gallery reads as several photographs of one saree rather than four
   unrelated graphics.
   ------------------------------------------------------------------------- */
function buildCloth(spec, size) {
  const rng = makeRng(spec.slug);
  // Motif size is fixed, so a bigger cloth means a finer-grained weave in the
  // crop. Editorial pieces use a larger cloth than product shots for exactly
  // this reason — a hero banner should not look like a macro photograph.
  const W = size?.W ?? 1000;
  const H = size?.H ?? 1400;
  const light = luma(spec.body) > 0.6;

  // Light cloth is shaded with its own darker tone; dark cloth catches highlight.
  const shade = light ? mix(spec.body, '#000000', 0.16) : mix(spec.body, '#000000', 0.42);
  const glow = light ? mix(spec.body, '#ffffff', 0.5) : mix(spec.body, '#ffffff', 0.22);

  const BORDER_W = 168; // korvai border running down the selvedge
  const PALLU_H = 400; // dense zari end-piece

  let defs = '';
  let body = '';

  /* --- fine warp/weft weave, the texture that makes it read as silk ----- */
  defs += `<pattern id="weave" width="8" height="8" patternUnits="userSpaceOnUse">
      <rect width="8" height="8" fill="none"/>
      <path d="M0 0H8" stroke="#ffffff" stroke-width="0.6" opacity="${light ? 0.22 : 0.07}"/>
      <path d="M0 4H8" stroke="#000000" stroke-width="0.6" opacity="0.05"/>
      <path d="M0 0V8" stroke="#000000" stroke-width="0.5" opacity="0.055"/>
    </pattern>`;

  /* --- light falling across the drape ----------------------------------- */
  defs += `<linearGradient id="drape" x1="0" y1="0" x2="1" y2="0.35">
      <stop offset="0%" stop-color="${shade}" stop-opacity="0.72"/>
      <stop offset="16%" stop-color="${glow}" stop-opacity="0.30"/>
      <stop offset="31%" stop-color="${shade}" stop-opacity="0.50"/>
      <stop offset="47%" stop-color="${glow}" stop-opacity="0.34"/>
      <stop offset="63%" stop-color="${shade}" stop-opacity="0.44"/>
      <stop offset="79%" stop-color="${glow}" stop-opacity="0.26"/>
      <stop offset="100%" stop-color="${shade}" stop-opacity="0.66"/>
    </linearGradient>`;

  /* --- zari thread: metallic, never flat ------------------------------- */
  defs += `<linearGradient id="zari" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="${mix(spec.zari, '#000000', 0.3)}"/>
      <stop offset="34%" stop-color="${spec.zari}"/>
      <stop offset="52%" stop-color="${mix(spec.zari, '#ffffff', light ? 0.18 : 0.55)}"/>
      <stop offset="70%" stop-color="${spec.zari}"/>
      <stop offset="100%" stop-color="${mix(spec.zari, '#000000', 0.26)}"/>
    </linearGradient>`;

  defs += `<linearGradient id="vignette" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#000000" stop-opacity="0.22"/>
      <stop offset="34%" stop-color="#000000" stop-opacity="0"/>
      <stop offset="100%" stop-color="#000000" stop-opacity="0.26"/>
    </linearGradient>`;

  /* --- ground ----------------------------------------------------------- */
  body += `<rect width="${W}" height="${H}" fill="${spec.body}"/>`;
  body += `<rect width="${W}" height="${H}" fill="url(#weave)"/>`;

  /* --- body buttas, in offset rows the way a real loom sets them out ---- */
  const draw = motifs[spec.motif] ?? motifs.lotus;
  const stepX = 176;
  const stepY = 208;
  let buttas = '';
  for (let row = 0; (row - 1) * stepY < H + stepY; row++) {
    const y = row * stepY - 60;
    const offset = row % 2 === 0 ? 0 : stepX / 2;
    for (let col = -1; col * stepX + offset < W - BORDER_W + stepX; col++) {
      const x = col * stepX + offset + 62;
      if (x > W - BORDER_W - 24) continue;
      if (y > H - PALLU_H - 30) continue;
      // The plume fan reads small at the shared radius, so give it more room.
      const r = (spec.motif === 'peacock' ? 33 : 27) + rng() * 5;
      buttas += `<g transform="rotate(${(rng() * 6 - 3).toFixed(1)} ${x.toFixed(0)} ${y.toFixed(0)})">${draw(x, y, r)}</g>`;
    }
  }
  // Pale grounds need the motif carried at near-full strength to stay legible.
  body += `<g fill="url(#zari)" color="${spec.zari}" opacity="${light ? 0.96 : 0.78}">${buttas}</g>`;

  /* --- pallu: the dense zari end-piece ---------------------------------- */
  const py = H - PALLU_H;
  body += `<rect x="0" y="${py}" width="${W}" height="${PALLU_H}" fill="${spec.border}"/>`;
  body += `<rect x="0" y="${py}" width="${W}" height="${PALLU_H}" fill="url(#weave)"/>`;
  // zari stripe sequence — thick, thin, thin, thick
  let stripes = '';
  const seq = [7, 2, 2, 11, 2, 2, 7, 3, 16, 3, 5];
  let sy = py + 26;
  for (const t of seq) {
    stripes += `<rect x="0" y="${sy.toFixed(1)}" width="${W}" height="${t}" opacity="${t > 6 ? 0.95 : 0.62}"/>`;
    sy += t + 15;
  }
  // a row of larger motifs across the pallu
  const palluCount = Math.max(1, Math.round(W / 168));
  for (let i = 0; i < palluCount; i++) {
    const x = (W / palluCount) * (i + 0.5);
    stripes += `<g opacity="0.9">${draw(x, py + 300, 44)}</g>`;
  }
  stripes += `<path d="${templeTeeth({ x: 0, y: py + 4, width: W, height: 22, count: Math.round(W / 29) })}" opacity="0.9"/>`;
  body += `<g fill="url(#zari)" color="${spec.zari}">${stripes}</g>`;

  /* --- korvai border down the selvedge ---------------------------------- */
  const bx = W - BORDER_W;
  body += `<rect x="${bx}" y="0" width="${BORDER_W}" height="${H}" fill="${spec.border}"/>`;
  body += `<rect x="${bx}" y="0" width="${BORDER_W}" height="${H}" fill="url(#weave)"/>`;
  let border = '';
  // temple teeth pointing into the body, drawn rotated into the vertical band
  border += `<g transform="rotate(90 ${bx} 0) translate(0 ${-bx})"><path d="${templeTeeth({ x: 0, y: bx - 36, width: H, height: 34, count: Math.round(H / 30), flip: true })}" opacity="0.92"/></g>`;
  // pinstripes along the border
  [14, 26, 140, 152].forEach((o, i) => {
    border += `<rect x="${bx + o}" y="0" width="${i === 1 || i === 2 ? 5 : 2.5}" height="${H}" opacity="0.8"/>`;
  });
  // a chain of motifs running the length of the border
  for (let i = 0; i * 118 < H; i++) {
    border += `<g opacity="0.88">${motifs.rudraksha(bx + BORDER_W / 2, 58 + i * 118, 26)}</g>`;
  }
  body += `<g fill="url(#zari)" color="${spec.zari}">${border}</g>`;

  /* --- a narrow contrast border on the opposite selvedge ---------------- */
  body += `<rect x="0" y="0" width="34" height="${H}" fill="${spec.border}"/>`;
  body += `<rect x="38" y="0" width="3" height="${H}" fill="${spec.zari}" opacity="0.65"/>`;

  /* --- final light pass over the whole cloth ---------------------------- */
  body += `<rect width="${W}" height="${H}" fill="url(#drape)" style="mix-blend-mode:soft-light"/>`;
  body += `<rect width="${W}" height="${H}" fill="url(#vignette)"/>`;

  return { defs, body, W, H };
}

/* -------------------------------------------------------------------------
   CROPS — each view is a window onto the same cloth.
   ------------------------------------------------------------------------- */
const VIEWS = {
  // Product gallery: full drape, border macro, pallu, body weave. All four are
  // windows onto one 1000x1400 cloth, so they read as one saree photographed
  // four times rather than four unrelated graphics.
  product: {
    crops: [
      { suffix: '-1', vb: [0, 0, 1000, 1333], w: 1000, h: 1333 },
      { suffix: '-2', vb: [620, 120, 380, 507], w: 760, h: 1013 },
      // Pallu crop must stay inside the cloth: the end-piece occupies y 1000–1400.
      { suffix: '-3', vb: [170, 1010, 292, 389], w: 760, h: 1013 },
      { suffix: '-4', vb: [160, 250, 420, 560], w: 840, h: 1120 },
    ],
  },
  // Editorial pieces render on a larger cloth so the weave stays fine-grained.
  // Hero: large enough that the weave is not a macro shot, tight enough that
  // the cloth still has presence behind the headline. The crop runs to the
  // right selvedge so the korvai border anchors that edge of the frame.
  hero: {
    cloth: { W: 1800, H: 1400 },
    crops: [{ suffix: '', vb: [0, 40, 1800, 1012], w: 1920, h: 1080 }],
  },
  portrait: {
    cloth: { W: 1150, H: 1700 },
    crops: [{ suffix: '', vb: [0, 40, 1050, 1400], w: 900, h: 1200 }],
  },
  square: {
    cloth: { W: 1500, H: 1700 },
    crops: [{ suffix: '', vb: [150, 300, 1100, 1100], w: 900, h: 900 }],
  },
  wide: {
    cloth: { W: 2200, H: 1500 },
    crops: [{ suffix: '', vb: [0, 150, 2200, 1375], w: 1760, h: 1100 }],
  },
  tall: {
    cloth: { W: 1200, H: 1800 },
    crops: [{ suffix: '', vb: [0, 90, 1120, 1680], w: 760, h: 1140 }],
  },
};

function emit(spec, view) {
  const config = VIEWS[view];
  const cloth = buildCloth(spec, config.cloth);
  return config.crops.map((v) => ({
    name: `${spec.slug}${v.suffix}.svg`,
    svg:
      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${v.vb.join(' ')}" width="${v.w}" height="${v.h}" preserveAspectRatio="xMidYMid slice" role="img">` +
      `<defs>${cloth.defs}</defs>${cloth.body}</svg>`,
  }));
}

/* -------------------------------------------------------------------------
   RUN
   ------------------------------------------------------------------------- */
const outProducts = join(ROOT, 'public', 'images', 'products');
const outEditorial = join(ROOT, 'public', 'images', 'editorial');
mkdirSync(outProducts, { recursive: true });
mkdirSync(outEditorial, { recursive: true });

let count = 0;
let bytes = 0;

for (const spec of SPEC.products) {
  for (const file of emit(spec, 'product')) {
    writeFileSync(join(outProducts, file.name), file.svg);
    count++;
    bytes += file.svg.length;
  }
}

for (const spec of SPEC.editorial) {
  for (const file of emit(spec, spec.view)) {
    writeFileSync(join(outEditorial, file.name), file.svg);
    count++;
    bytes += file.svg.length;
  }
}

console.log(`Generated ${count} artwork files (${(bytes / 1024).toFixed(0)} KB total).`);
console.log(`  products  -> public/images/products`);
console.log(`  editorial -> public/images/editorial`);
